# based on https://docs.github.com/en/actions/learn-github-actions/contexts#example-printing-context-information-to-the-log
name: dump context
on:
  # see all at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#available-events
  create:
  push:
  pull_request:
  release:
  schedule:
    - cron: "51 17 * * 3"  # once a week, https://crontab.guru/#51_17_*_*_3
  workflow_dispatch:
    inputs:
      example_string:
        type: string
        default: "example value"
      example_string_default:
        type: string
      example_choice:
        type: choice
        description: A choice input
        options:
        - choice_a
        - choice_b
        default: choice_a
      example_boolean:
        type: boolean
        description: A boolean input
        default: false
      environment:
        type: environment

jobs:
  dump_contexts_to_log:
    name: ${{ github.event_name }}
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          # avoid checking out the repository in a detached state
          # https://github.com/stefanzweifel/git-auto-commit-action/issues/70
          ref: main
      - name: Install Dependencies
        run: sudo apt-get install --yes jq gron
      # The `steps` context ONLY contains information about the steps in the
      # current job that have an `id` specified and have already run.
      # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#steps-context
      - name: Generate steps context
        id: step_foo
        run: echo "output_bar=example step output" >> "$GITHUB_OUTPUT"
      # Pass in context as environment variable so Bash can properly handle single quotes in the context content.
      # https://github.com/actions/runner/issues/1656#issuecomment-1030077729
      # https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#example-printing-context-information-to-the-log
      #
      # Note that the github context includes a token, but it is scrubbed from logs.
      # > Before each job begins, GitHub fetches an installation access token for the job.
      # > The GITHUB_TOKEN expires when a job finishes or after a maximum of 24 hours.
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT" | gron --no-sort
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - name: Dump job context
        run: echo "$JOB_CONTEXT" | gron --no-sort
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
      - name: Dump steps context
        run: echo "$STEPS_CONTEXT" | gron --no-sort
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
      - name: Dump runner context
        run: echo "$RUNNER_CONTEXT" | gron --no-sort
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
      - name: Dump strategy context
        run: echo "$STRATEGY_CONTEXT" | gron --no-sort
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      - name: Dump matrix context
        run: echo "$MATRIX_CONTEXT" | gron --no-sort
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      - name: Dump env context
        run: echo "$ENV_CONTEXT" | jq 'del(.ENV_CONTEXT)' | gron --no-sort
        env:
          ENV_CONTEXT: ${{ toJSON(env) }}
      - name: Dump inputs context
        run: echo "$INPUTS_CONTEXT" | gron --no-sort
        env:
          INPUTS_CONTEXT: ${{ toJSON(inputs) }}
      - name: Dump all contexts to a file
        run: |
          echo "{\"github\": $GITHUB_CONTEXT," > contexts.json
          echo "\"job\": $JOB_CONTEXT," >> contexts.json
          echo "\"steps\": $STEPS_CONTEXT," >> contexts.json
          echo "\"runner\": $RUNNER_CONTEXT," >> contexts.json
          echo "\"strategy\": $STRATEGY_CONTEXT," >> contexts.json
          echo "\"matrix\": $MATRIX_CONTEXT," >> contexts.json
          # NOTE: this final line uses a different syntax: ' }' instead of ',' suffix
          echo "\"inputs\": $INPUTS_CONTEXT }" >> contexts.json
          jq '.github.token = "***"' contexts.json > contexts/${{ github.event_name }}.json
          rm contexts.json
          # gron --no-sort option is unstable https://github.com/tomnomnom/gron/issues/102
          gron contexts/${{ github.event_name }}.json > contexts/${{ github.event_name }}.gron
          gron --no-sort --colorize contexts/${{ github.event_name }}.json
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          JOB_CONTEXT: ${{ toJSON(job) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
          INPUTS_CONTEXT: ${{ toJSON(inputs) }}
      - name: Set current date
        run: echo "CURRENT_DATE=$(date --utc --iso)" >> "$GITHUB_ENV"
      - name: Deploy contexts
        # skip deployment on "pull_request" events not triggered by repo
        # owner, which usually failed due to no permission
        if: |
          ! (
            github.event_name == 'pull_request' &&
            github.repository_owner != github.triggering_actor
          )
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "contexts for ${{ github.event_name }} on ${{ env.CURRENT_DATE }}\n\n${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}\n\n[skip ci]"
          skip_checkout: false
          branch: main
